---
apiVersion: v1
kind: Namespace
metadata:
  name: openspeedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  namespace: openspeedtest
spec:
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
        - name: openspeedtest
          image: openspeedtest/latest:v2.0.6
          ports:
            - name: http
              containerPort: 3000
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt/nfs
              name: openspeedtest-volume
      volumes:
        - name: openspeedtest-volume
          persistentVolumeClaim:
            claimName: openspeedtest-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
  namespace: openspeedtest
  labels:
    app: openspeedtest
spec:
  type: ClusterIP
  selector:
    app: openspeedtest
  ports:
    - port: 30000
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openspeedtest
  name: openspeedtest-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: default
