---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  hostname: tailscale-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "192.168.0.0/24"
  proxyClass: default-proxy-class
