---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
  namespace: tailscale
spec:
  # when a single replica goes down, others jump in
  replicas: 6
  subnetRouter:
    advertiseRoutes:
      # my local network CIDR
      - "192.168.0.0/24"
  proxyClass: subnet-router-proxy-class
