---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.92.5
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
