- name: Install nfs-common on all hosts
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present
        update_cache: yes
