apiVersion: v1
kind: Secret
metadata:
    name: telegram-bot-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:faJVSJZlNAtJuIxvLqBg1jp0SBo9BXAp6uhrxyIEI+48NXKLxRGfGbS7PNwRVA==,iv:Fe5e1zYFstPQxc9kxPd19OyzhK/ekdJLZBqgilIaFWE=,tag:4erhinFtqT1aNVXDrgB5qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVUtmNm91RjkwYUQyNFVw
            T1pXdFRULy9TenpkK1Y5V1FZM2kybHZJYVhVCnlCOUE3aktXSjExT1FQRzllbmlz
            RGFYUDZsWkE5Ulc4STBNc2RvTFZLVk0KLS0tIDdPaFhSTjJsbE81TnZLWnREa2hB
            OWRuVklvVTVkU0ZTL1hxMGQzcDEyL0UKSqVdcZMGrvBAhPSDkYbxrrNIcWJ0Q/b7
            Vzt4WlkmPiw52BimeYGzXqs0yBf1brOTmmm8xccb9saEKPXvGi90nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T17:57:42Z"
    mac: ENC[AES256_GCM,data:tMO1yoVptXA4Mm7gMnoiAUvAHuBS3VwZctxqH2HOlb3Ymq1/aFBx248RIN2YZFYV23WH5KL4Jj9q0R4hY/zjmlajWaq9Ylp6YS5z/isfNPjFOgMLQK6BK3eQ5FGDgqEi20zESuKosPiMAwRP+r8sTirIPw4dDYbabafdSj5ZRmY=,iv:+NbJqdmhyEqTybzlF/1C1swDw8nLXc0LoOTFtBcSLfA=,tag:yK/HWoR2mJKMiwaRS37jmA==,type:str]
    version: 3.13.3
