---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: ghcr.io/fallenbagel/jellyseerr:2.7.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5055
          envFrom:
            - configMapRef:
                name: jellyseerr-config
          volumeMounts:
            - name: jellyseerr-data
              mountPath: /app/config
      volumes:
        - name: jellyseerr-data
          persistentVolumeClaim:
            claimName: jellyseerr-data
