apiVersion: v1
kind: Node
metadata:
  name: k3s-postgres-agent-1
  labels:
    node-role.kubernetes.io/postgres: ""
spec:
  taints:
  - key: "node-role.kubernetes.io/postgres"
    value: "true"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Node
metadata:
  name: k3s-postgres-agent-2
  labels:
    node-role.kubernetes.io/postgres: ""
spec:
  taints:
  - key: "node-role.kubernetes.io/postgres"
    value: "true"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Node
metadata:
  name: k3s-postgres-agent-3
  labels:
    node-role.kubernetes.io/postgres: ""
spec:
  taints:
  - key: "node-role.kubernetes.io/postgres"
    value: "true"
    effect: "NoSchedule"
