resources:
  - ./openspeedtest
  - ./it-tools
  - ./miniflux
  - ./paperless-ngx
  - ./recipes
  - ./vaultwarden
  - ./jellyfin
  - ./jellyseerr
  - ./radarr
  - ./sonarr
  - ./prowlarr
  - ./sabnzbd
  - ./gotify
  - ./apprise
