---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-certificate
  namespace: default
spec:
  secretName: cloudflare-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.maurovi.ch"
