apiVersion: v1
kind: Secret
metadata:
  name: homelab-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/paulmaurovich/homelab.git
