apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secrets
  namespace: miniflux
  labels:
    app: miniflux
type: Opaque
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:I5tRTV0DgRSUs6WMVQ==,iv:0A1sWwbji8bZSuGo3xOVGNo+YT6nnIdz3wVcsg6cRLM=,tag:PPJE9Onu8qerhAHXnPh+ZA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:c8ouxrW7Mln5nOaa4rCinhMYZyNRN/XcRA==,iv:2b/EdZ+vUr08F4CHMtNp7r7tB1VhTLdMs2AoGA6tGAs=,tag:BPR5Sx1s2NpSPnlo+5vjow==,type:str]
sops:
  age:
    - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dXk0d1A1NHFneG5oT1RF
        MlI3MmJnSmUxSDVDY2hMMmZoNzBBeE9ydlZBCks2UktZWG85bU5IbWEvenpzOGVa
        Mi8wVzRBZzdiRERXaEQvYnI1QS84NGMKLS0tIDRJY0t6aG5uQWhUanVzK3pGbm9I
        SE1rNjhxc3dFb25meXliMVdQQzRNVWMKjClDGpJOuuXNpQwfWAzvXW2gBp2CGPw4
        0UX68LixjnHigo/T3UxcxNFBErL1uAka5yaBD4P/wJ7BvCnPaFQ8RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-26T14:48:05Z"
  mac: ENC[AES256_GCM,data:zXGgMngAGPRjakvc4Rww99Kw2zphPWXyw7fn3Oq3Gr1SlvHxHKGaIqESp9mJ+Nz/C11/TcHFA04JX7qpK3Rk4jwSSS67MMbel9sLKAdheBWPw9EOiRI1oEtgUkvWcN9fnBYw6rcptqfoeKuH5S5cR9I3LYfGeJRWDDfQUQ5D2Aw=,iv:PaHeKxcHriKnmNn5n5k6Psvj1ZA2+gGRKn76WipjkAw=,tag:elb+gaNz54tij02Y6iyaIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
