---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-data
  namespace: portainer
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/portainer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data
  namespace: portainer
spec:
  volumeName: portainer-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: ""
