keepalived_pass: ENC[AES256_GCM,data:BL7p2vr7Gi/kgr+lA1W84CirOzg=,iv:58QAbl74YiuklnG2mweTp41tLTw0Tq7HivUXtvH5hKE=,tag:0NiRueDqOVXzMoy8Ma0TPQ==,type:str]
keepalived_virtual_ip: ENC[AES256_GCM,data:sm4aOL34kD855igEw1Hb,iv:3L0u8knx3wvBlxzB21TKXLNxN1H1JGSfDuiVmdj2GIc=,tag:+T9YSKe5xobtpFjUwpCAwA==,type:str]
keepalived_interface: ENC[AES256_GCM,data:KxS2Lg==,iv:ZeLXRrXN/hnHmRpr7yQHWv5kDHFLtcZQCZA0oJ3tuos=,tag:oSMzCpm8q+od7o5mroK0+Q==,type:str]
keepalived_virtual_router_id: ENC[AES256_GCM,data:q2Q=,iv:errfqVj8bgE5ZF3+OPQCSBt+gvbYdvuA0XuwFUfe01A=,tag:rhWX27SXkNJ2brEnCrw62g==,type:int]
keepalived_master_ip: ENC[AES256_GCM,data:HJOla3NBfbGTFPPd,iv:7I78RyOwyJqYy7/PvWbAzrto5sKwDzJEKfhrlx85cEs=,tag:0mhP1pCjNKv4V741BRGluA==,type:str]
keepalived_backup1_ip: ENC[AES256_GCM,data:Z3H39dkFYM5BSjax,iv:DVNSnifJbdMbQr3rTjdI/JJRZK1qJ/qAxCzjsGdp3aU=,tag:8kgyMLZVR78FcM4cJvUIAw==,type:str]
keepalived_backup2_ip: ENC[AES256_GCM,data:R2B3TdCjvF4sX9jl,iv:SzJe2YFRWGhB8vDhKNVs2Msa/pKrXJ1LGi90Ci/0mxo=,tag:hFJH5SqUioFjovz9Rdr64g==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ013ZVlIcU5CWjA2U2VD
            RUM0LzlCcWUzdklJS1NqNnlpYVYyKzJKUVNrCk1EWjlvYVk3bzNQb2NCYXpWTXVw
            MzZUTVZ4NnVQR05uaDZmaCtCQWpJQ0EKLS0tIEJaWkRqYlJIejhxNXFWMW95QjJ4
            MFRWcnI5cHRxcTZtNDk2Z2dQNVdPRXMK1ePW2lR4qWYt+zNugCTXkYZx7fvx4TnW
            pxnrXj1iCz2ZMEOCYv1mrLqKQLe3iS9Is5aQTBN8Q+TItuXUdurA9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T19:32:21Z"
    mac: ENC[AES256_GCM,data:f6W/B8rjCpsSOAsJbRYjfDMfO0z8lMAJz2Bi9A/dexrTu9La9B21F7UygQpTvQlg6q4gNAUnn6oJW+4eibQgOfVSV2pPnemzPTNwuz2uiBXBbltrrnUVhsf/7I2xRPg9dAKYjUJvzvuokaUYMcwpHAGYx7rnMHQKh3OvhSEKUPA=,iv:LlyVsMnJnw1grKr3GKggTi0AG5PyF30e19ic30NE1tw=,tag:F1UHWPOfCye8giYzb/qH/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
