---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgresql-cluster
  namespace: cnpg-system
spec:
  instances: 3
  storage:
    storageClass: local-path
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  enableSuperuserAccess: true
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
