---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgresql-cluster
  #annotations:
  #  cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: local-path
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule
