---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 5m
  url: https://ghcr.io/cloudnative-pg/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnpg-system
  releaseName: plugin-barman-cloud
