---
apiVersion: v1
kind: Service
metadata:
  name: beszel-hub
  namespace: beszel
spec:
  type: ClusterIP
  selector:
    app: beszel-hub
  ports:
    - name: http
      port: 80
      targetPort: 8090
