---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: promtail
      version: 6.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    daemonset:
      enabled: true
    clients:
      - url: http://loki.loki.svc.cluster.local/loki/api/v1/push
        tenant_id: 1
    # allow promtail to be scheduled on all nodes (even/especially postres workers)
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/postgres
