apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: homarr
type: Opaque
stringData:
    db-encryption-key: ENC[AES256_GCM,data:COUshsKPnd/FOWVSS8OsD0mZwypeQnnPugGHFCn17NQFAs4QFHkLKuD3zYhligaTTtcyqbFjRu4HdWzVk5VN3w==,iv:98sOWkgxyebmzOkKdaDpc1cKYM0MOqsoC+GsiAGQ7QM=,tag:XHhfcbtclOX/GbxOXHakIg==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSFp4UFFNSjFmNmdZWEpG
            MGNabXkrbUVyOWtBZWpCeVF1RXQyQ0xxbW1rCmloYWlEL1NEb1BLY1d1bVlNQ21z
            U3pBMmo0MkZkdm8rM3hMYzJKWkE4K0UKLS0tIDJVRVIyZ0d2SjQzSElscFhGanlY
            RGY1d1ZaNFNwTnpqTnArbUtPUEM5T2cKA2Wl/F9nn/YK1aw7AIXJpQZcqFaAQJS6
            K3mwgbRuOHN8t0ZzbJ3B/zHhRlrUT8vN/q688vKh18eth9TdIPeynA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T19:20:34Z"
    mac: ENC[AES256_GCM,data:J4Kk6p4FT9cY0Kbzm80m6cybdm0HBF32fU386x3wUY1rWgpn/Oi0AjnzqbFUGL9/a93Ex0w/+MToOAlMkunojGt4+M9mr1JVWER6luMexKKtT3lriVWm1xGtRkz6S5u8GgOaEhW3Qc++uVZmqqWV6VKNVsdzNf4AUQQy3jD2vHo=,iv:5Ps4bk/+79E3tRRWin7xHffOY2Hv2jES2+cmT2iSxlE=,tag:hoNB2J2O6tmn0BmSpxkcJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
