---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: external-routes
spec:
  ports:
    - port: 80
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  namespace: external-routes
subsets:
  - addresses:
      - ip: 192.168.0.30
    ports:
      - port: 80
        name: http
