---
- name: Install and configure HAProxy on LB nodes
  hosts: k3s_ha_proxies
  become: true

  tasks:
    - name: Install SOPS
      ansible.builtin.import_tasks:
        file: ../install-sops-on-remote.yaml

    - name: Load encrypted variables
      community.sops.load_vars:
        file: secrets/ha-proxy-secrets.enc.yaml

    - name: Check if HAProxy is installed
      command: haproxy -v
      register: haproxy_installed
      ignore_errors: yes
      changed_when: false

    - name: Install HAProxy
      package:
        name: haproxy
        state: present
      register: haproxy_install
      when: haproxy_installed.rc != 0

    - name: Deploy HAProxy configuration
      template:
        src: config/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start HAProxy service
      systemd:
        name: haproxy
        state: restarted
        enabled: yes

    - name: Verify HAProxy is running
      command: systemctl status haproxy
      register: haproxy_status
      changed_when: false

    - name: Display HAProxy status
      debug:
        msg: "{{ haproxy_status.stdout_lines }}"
