---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads
  namespace: radarr
spec:
  capacity:
    storage: 300G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/media-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
  namespace: radarr
spec:
  volumeName: radarr-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300G
  storageClassName: ""
