---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies
  namespace: radarr
spec:
  capacity:
    storage: 1800G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool0/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: radarr
  name: radarr-movies
spec:
  volumeName: radarr-movies
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1800G
  storageClassName: ""
