---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-data
  namespace: radarr
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: radarr
spec:
  volumeName: radarr-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: ""
