---
- name: Resize LVM volumes to utilize all available disk space
  hosts: k3s_cluster
  become: true
  gather_facts: true

  vars:
    lvm_path: /dev/ubuntu-vg/ubuntu-lv
    expected_filesystem: ext4

  tasks:
    - name: Gather LVM volume information
      command: lvdisplay {{ lvm_path }}
      register: lv_info
      changed_when: false
      failed_when: lv_info.rc != 0
      
    - name: Display current LVM status
      debug:
        msg: "Current LVM status for {{ lvm_path }}:\n{{ lv_info.stdout }}"
    
    - name: Check filesystem type
      command: df -T {{ lvm_path }}
      register: fs_type
      changed_when: false
      failed_when: false
      
    - name: Verify ext4 filesystem
      assert:
        that:
          - "expected_filesystem in fs_type.stdout"
        fail_msg: "The filesystem is not ext4 as expected! Found: {{ fs_type.stdout }}"
        success_msg: "Confirmed ext4 filesystem, proceeding with resize"
    
    - name: Extend logical volume to use all free space
      command: lvextend -l +100%FREE {{ lvm_path }}
      register: lv_extend
      failed_when: lv_extend.rc != 0 and "not found" not in lv_extend.stderr
      changed_when: lv_extend.rc == 0
      
    - name: Display LV extend results
      debug:
        msg: "{{ lv_extend.stdout | default('No additional space available for extending LVM') }}"
      when: lv_extend.changed
      
    - name: Resize ext4 filesystem
      command: resize2fs {{ lvm_path }}
      register: resize_result
      changed_when: '"Nothing to do" not in resize_result.stdout and resize_result.rc == 0'
      failed_when: resize_result.rc != 0
      
    - name: Display filesystem resize results
      debug:
        msg: "{{ resize_result.stdout }}"

    - name: Verify current disk usage
      command: df -h
      register: disk_usage
      changed_when: false
      
    - name: Display current disk usage
      debug:
        msg: "Current disk usage:\n{{ disk_usage.stdout }}"

  post_tasks:
    - name: Summary of actions taken
      debug:
        msg: |
          Disk resize operation completed:
          - Logical volume: {{ lvm_path }}
          - LV extended: {{ lv_extend.changed | ternary('Yes', 'No change needed') }}
          - Filesystem resized: {{ resize_result.changed | ternary('Yes', 'No change needed') }}

