---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data
  namespace: pgadmin
spec:
  capacity:
    storage: 512M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/pgadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: pgadmin
spec:
  volumeName: pgadmin-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512M
  storageClassName: ""
