---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "05.linings-minke@icloud.com"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare
    solvers:
      - dns01:
          cloudflare:
            email: "05.linings-minke@icloud.com"
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---

