apiVersion: v1
kind: Secret
metadata:
    name: sonarr-db-secrets
    namespace: sonarr
type: Opaque
stringData:
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:Rn99GYCEHWZ76CzQd6ce6Sy769BoZXegE1diE6jlbEh2rOqG1EtJShcpJdIwcLLxnuEdj+HP,iv:zvNBshfSJkGgR1MJJzGIjb9cUQpG9FS6Pq6nW6XyPXE=,tag:QFGSQcgn3sqGpd7CYDbsHg==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:otYMZQ==,iv:+xG/zi9kK+hwpZ3lqc66OQJNOovvreY/dbYlbynqt5w=,tag:DMnhn0ruILisT7XcW1o/mQ==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:P4Smk6a8,iv:U7HZ6vPdHGLLSaZMa6egXS2FNJ4I4jMvelSfCig6emk=,tag:z8kHqWr9TovljSGItKbM2w==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:JQWrhc+Jjdo0v6xqHWLrkLC3T2Um5WfuNT9ZKM9xBP0YsQW2iv4ZF9T8k+r9wBf/RVU=,iv:qu7/zVtpOzfWrLtQwnkRkbIIHpNK49YgNR+3eWyDtKg=,tag:NrkG9SN/T9/D4lM6LAqFZw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:NTXptlFS,iv:nkgBBNILP1FyiqxNDn5R1jjfuKbkUGO6Wd/0P/zJPgA=,tag:eecFZjtXYT8mMC4bRGtYwQ==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY3QreG9YYkhNdXcvRzkr
            c256VTMxdHJZUmV0MjYvTVRidlRTWXR0KzNVCmhJT1hkTjRpcEp6TlhWTUhGbTE5
            QVpFdHJWUFFhb2tJTGJKRjlFcVM5d0UKLS0tIFRmSlRGV0luc3BrQnN0N1lUY1JP
            bHBkNUxjc3RCSWR5ak12NzlRMktTZk0KvSEYKZy0U/2PCSVSwH03Eb90ePLAcgx3
            p7MEW3L/oK3pfAfg9xVPH/0qD2nlLGeo/gJNKXCry3WWNp/lr1Hc5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T14:56:53Z"
    mac: ENC[AES256_GCM,data:6DTkk30C28LM2Ft2iNCZl552iYQcP5HFQercMB2nwfM3Q+SU6afW3cCGk5e1VVqqPn7kAXSvpQllpjI5wKeM9H5lMOo2inTMapkrfgxqPg0UbHyoBiBy/Jfm7mBOMhlpKHTTHD4zJTNSI9/0rKyir4YbPvmS1jAd5OYEfU82Gnk=,iv:QcL7gMeiucIxXyM0KL+4hTUuO61szd4gKxfHWlk3yUo=,tag:/QKo8wZcv+KkKgETgEdPqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
