---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: loki
      version: 6.51.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: "filesystem"
      schemaConfig:
        configs:
          - from: "2025-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: true

    minio:
      enabled: false

    singleBinary:
      replicas: 1
      persistence:
        # If set to 'true' the charts will create a PVC named storage
        # (which results in storage-loki-0)
        enabled: true

    # It is necessary to zero out replica counts of other deployment modes
    # when using 'singleBinary', otherwise, the deployment will fail.
    test:
      enabled: false
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
