---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apprise-data
  namespace: apprise
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/apprise
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-data
  namespace: apprise
spec:
  volumeName: apprise-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
