---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:2.2.0-nightly
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9696
          envFrom:
            - configMapRef:
                name: prowlarr-config
            - secretRef:
                name: prowlarr-db-secrets
          volumeMounts:
            - name: prowlarr-data
              mountPath: /config
      volumes:
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-data
