---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/jellyfin/cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: jellyfin-cache
spec:
  volumeName: jellyfin-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50G
  storageClassName: ""
