---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-data
  namespace: jellyfin
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/jellyfin/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: jellyfin-data
spec:
  volumeName: jellyfin-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: ""
