---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: intel-devices
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gpu-device-plugin
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: intel-devices
  values:
    image:
      tag: 0.34.0
