---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
data:
  DOMAIN: vaultwarden-prod.maurovi.ch
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOW: "false"
  SENDS_ALLOWED: "false"
