---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: homarr
      version: 5.13.0
      sourceRef:
        kind: HelmRepository
        name: homarr-labs
        namespace: homarr
  releaseName: homarr
  # https://github.com/homarr-labs/charts/blob/d3108450ece04e23e1f97ea7b8c193a8fd536fe6/charts/homarr/values.yaml
  values:
    env:
      TZ: Europe/Vienna
    image:
      tag: v1.38.0
    persistence:
      homarrDatabase:
        enabled: true
        name: "homarr-database"
        storageClassName: ""
        accessMode: "ReadWriteMany"
        size: "1G"
        mountPath: "/appdata"
        volumeClaimName: "homarr-database"
