---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: recipes
spec:
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      containers:
        - name: recipes
          image: ghcr.io/tandoorrecipes/recipes:2.6.7@sha256:506a92474be39e8fd3b896fcf25132ea11c28f885dfc7a8f0e9d9e5f88056434
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 700Mi
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: recipes-secrets
          volumeMounts:
            - mountPath: /opt/recipes/staticfiles
              name: recipes-staticfiles
            - mountPath: /opt/recipes/mediafiles
              name: recipes-mediafiles
      volumes:
        - name: recipes-staticfiles
          persistentVolumeClaim:
            claimName: recipes-staticfiles
        - name: recipes-mediafiles
          persistentVolumeClaim:
            claimName: recipes-mediafiles
