---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: recipes
spec:
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      containers:
        - name: recipes
          image: ghcr.io/tandoorrecipes/recipes:2.6.4@sha256:8ab96a23f16b80531a82aee6b18d5afb5c6a9adaa09c46c7b832e92f85bb00b8
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 700Mi
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: recipes-secrets
          volumeMounts:
            - mountPath: /opt/recipes/staticfiles
              name: recipes-staticfiles
            - mountPath: /opt/recipes/mediafiles
              name: recipes-mediafiles
      volumes:
        - name: recipes-staticfiles
          persistentVolumeClaim:
            claimName: recipes-staticfiles
        - name: recipes-mediafiles
          persistentVolumeClaim:
            claimName: recipes-mediafiles
