---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: recipes
spec:
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      containers:
        - name: recipes
          image: ghcr.io/tandoorrecipes/recipes:2.5.3@sha256:7ce6534c9ab0e471fd0f08add67e871b9173fb580c2f86294c3ead025603a3d7
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 700Mi
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: recipes-secrets
          volumeMounts:
            - mountPath: /opt/recipes/staticfiles
              name: recipes-staticfiles
            - mountPath: /opt/recipes/mediafiles
              name: recipes-mediafiles
      volumes:
        - name: recipes-staticfiles
          persistentVolumeClaim:
            claimName: recipes-staticfiles
        - name: recipes-mediafiles
          persistentVolumeClaim:
            claimName: recipes-mediafiles
