---
apiVersion: v1
kind: Node
metadata:
  name: k3s-server-1
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-pool: servers
spec:
  taints:
    - key: "node-role.kubernetes.io/control-plane"
      effect: "NoSchedule"
      value: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: k3s-server-2
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-pool: servers
spec:
  taints:
    - key: "node-role.kubernetes.io/control-plane"
      effect: "NoSchedule"
      value: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: k3s-server-3
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-pool: servers
spec:
  taints:
    - key: "node-role.kubernetes.io/control-plane"
      effect: "NoSchedule"
      value: "true"
