---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: miniflux/miniflux:2.2.14
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: miniflux-config
            - secretRef:
                name: miniflux-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app: miniflux
spec:
  type: ClusterIP
  selector:
    app: miniflux
  ports:
    - port: 80
      targetPort: 8080
      name: http
