---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: miniflux/miniflux:2.2.11
          ports:
            - name: http
              containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cn-postgresql-cluster-app
                  key: uri
          envFrom:
            - configMapRef:
                name: miniflux-config-prod
            - secretRef:
                name: miniflux-secrets-prod
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app: miniflux
spec:
  type: ClusterIP
  selector:
    app: miniflux
  ports:
    - port: 30000
      targetPort: 3000
      name: http
