---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: miniflux/miniflux:2.3.3@sha256:49d7b60987616387c306a8023087b31f2c9b7b21288b523026cb04058e8b6dbb
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: miniflux-config
            - secretRef:
                name: miniflux-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app: miniflux
spec:
  type: ClusterIP
  selector:
    app: miniflux
  ports:
    - port: 80
      targetPort: 8080
      name: http
