---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: gotify
spec:
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: ghcr.io/gotify/server:2.7.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: db-secrets
            - secretRef:
                name: basic-auth
          volumeMounts:
            - name: gotify-data
              mountPath: /app/data
      volumes:
        - name: gotify-data
          persistentVolumeClaim:
            claimName: gotify-data
