---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 5h
  timeout: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: node-feature-discovery
