apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: beszel-agent-secrets
    namespace: beszel
stringData:
    KEY: ENC[AES256_GCM,data:/H/ek4knzfJTgiShzeaf1tJlUoh4nqW0B4WISpz6tQK0rX/QBQe5hVPI34o+cH2y5+kpVe+wWvSlNZSR11TsWbhgivprY1wqFdtPc2G33KI=,iv:8xLmN1WEllbypw9OCFPEUlxUt3sjl2CyAIUczugtwuc=,tag:QdhwPegPDZ5rLQXSehkeMg==,type:str]
    TOKEN: ENC[AES256_GCM,data:abQnz2h0nTWvI5VN+lhfRZfpvokquiywxke4XHixEDnL4jJt,iv:ZXgbDSJpEk0ILXet2H+dV728v5qR7OdGZAv1nIb5mbQ=,tag:1kUGyvmPezqqKh8ZfXXQrA==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMkFCMTN5WUF0MEVkV2tD
            d3ZxRGF6ekI3cmNQRzhoZ3lLUUI4VC9MT1N3CjVPMzVESjFNWm5VekhkYlhpTVlX
            UEc2ZGZzUGxXbHh1cURSQkU3WXcxUkEKLS0tICtxVU8wTUZCRnNPRjhvem8xUHhS
            VXBXdUtGcUo5eVRla2cwMTZ6Nk5qRGMKRhzD9qhH73O1W9IlNNpdRkWTFx4L6IU+
            hJHlFpEADDPXnGA7sGbNGLl9R+yGJ/6eRiyoDWKJNimdcuq7VYp+lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T19:17:25Z"
    mac: ENC[AES256_GCM,data:GkSGv5HC0PBKWgqxwYa513TESbWR9Q4T1OeXaFtj+nfrNr3Hnag8bq4J+HoBNVGpWwn2sZLr0iuZYH4+QlqpFdUTFpaE417Yv/Hn11wuVnIGTjvflFOb3EH2NyyEyD5R4aFUf/z2CL4nxlDUoeXJi9+Xwj4WPgLCpDs2cM/x2Ek=,iv:hDigqeDgtV1GIQ4CfbHEVarfDGX+z+viquuCLcvA1HU=,tag:bZNj67c370UNGPJkshspjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
