apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: gatus
type: Opaque
stringData:
    POSTGRES_CONNECTION_STRING: ENC[AES256_GCM,data:GF5h1lDe0uKNz83P2tCgRtZoPK7YcBQZJ5QG/DiWTJxOOoBmZMIAt7jA9iMecuKT/yFLYzEQWqoGILtp9W1sFe2XIZob/X7XzITGv6qvqOSsoc3HaxdtD6d3NHqA4Po8nDdnP+OhKNP2,iv:6MoT10XhB/qjkzgABP9tbP48Bix/IkPjvpFTdAVRWy4=,tag:F51BTdTDjjCSSu19NN0x9Q==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU2R2K2kzTXp0V2NhVGVN
            SGZLY0pBckVZNDNPcXJUTm9zK1dRb2wwSkJnCmZYUTg5ZWE4SExUb0dZRVhYamtX
            NE5lT05KYnFJT2g3OTZDRVRwaWROUTAKLS0tIDA4VDdpQWZ4dXRJQ0k1QXFrNmk3
            aGhPUEVyMUUrMXlCMVZBUkUyd2FJZjAKrImhXWLo48V7Ci9LtHiGJ2PnQjXiVNhs
            c5pLOXPjwLWnJhQTxF1MLFf2CHRkLvVP+8j6uZ2koUK+8sIZSaHERA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T16:55:33Z"
    mac: ENC[AES256_GCM,data:fhQrvdTJjimJPUNlAO9cFCPG/ixP77ppdCIAEmPsolxs4RgGNKzjAuWgjyrc0VTB4+k/64Ctfk0SpElL6HSaJ5ommYwI89ZRWOu2nzfo9PIAwoyQY1blsrk9VCqTUJ5OC4aUBCwzIcNLAp3GrAfaaVVM8opLls0f3dyZ5AvKluY=,iv:pmImllMU/gPwH8ohZVQF5jiptk0CfUvvhpvmcpA5vQ0=,tag:k9WtEzO4FR8MQ1wWOaWObw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
