apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolation
spec:
  podSelector:
    matchLabels:
      isolated: "true"
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
