apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: v1
data:
  password: cGFzcw==
  username: dXNlcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: testing
  namespace: test
