apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:RjUJZ2NbFq2A1HTOaS3heXezRynNX/E6TLUpnq8X/CCTfRZ/kDiOt6Dn1hZGf4tEU7Amgameysa0x8j1foj7DMu54nQU4VDOanIlGpNSBAzeEfxqpibGKIp+3oIW,iv:HQpGvMTeRp9YljvACAiocr1UGKGS0eo/u0O0w1H478E=,tag:CzpAuFaSSOaFg+HEWpDuLA==,type:str]
    RENOVATE_USERNAME: ENC[AES256_GCM,data:GKLVsnPpoi5ZDweo6Q==,iv:wuIm3kqY/JLOnPZhXplPsV7fANeurJPWXhjcXR0bfB8=,tag:IXYkUPJS160R1wsMY8FocQ==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:G577+kQShbXQivxKPWJTC4UJruIYDqCmXbpgkD6q,iv:yzH0cnoX1Afhobg4BWpQi3P1zha2s6jzyVkrUsHYQ/A=,tag:CbL4YtXUkAKMo7xFwdBIMg==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ2hmSGM5QkhtZ3k2d21n
            UDJtamZGelhxcE9zTFM5ZlUraGUrSkZGM1NZCm9FMjBnbGY1L1JlV1g2Zi84Yk9G
            bWdVaVV6NXM2ZENsVVN6clNweVNhcHcKLS0tIERCVytBc1cvM3ZqelA2cmQ1MGYy
            YUJhK0NkZytPVStmc2FKaEJ3Q04yZWsKHsQcuFiB86edC9IKNWd7HMWfonnDMZn6
            Tz5xvAXN1JU0IgR6x1LqHxhok7DKPEyHY5LEOnh21jvCyppAQnkJRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T11:11:45Z"
    mac: ENC[AES256_GCM,data:l8bwqUZG5TjWheG5CXzRNRtImqaeSUmhtRoE/KZgbPrYhWIRt+WAse8GtrjP9C1MSP8W+puozqGqZr7Rfhtb7nV3dZoKbOymeFPviDz8zI+hBO4kaFF6fb+dWNBeF+7Qd2XNMgfa7gcOrUh4vNejyLHY+l51G0pvlwRrDEJsGII=,iv:tk2C2oHbd594aXgNMdPrb58hVhH/CRpbB/CWF1hbcNU=,tag:ZW77nr7Vy3esEFMN+9+Jdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
