apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:XKmqNlX2aAd2UUUIwbY/+/XmmwPjZcSRjadeHmXMPtxmlOqXYZDdpg==,iv:EcTg6k0l3bdjosq27lCDbXrnKXsMXIKubckHMQ03EuY=,tag:pgcyVKlz5kdCpoIIsvP8VQ==,type:str]
    RENOVATE_USERNAME: ENC[AES256_GCM,data:GKLVsnPpoi5ZDweo6Q==,iv:wuIm3kqY/JLOnPZhXplPsV7fANeurJPWXhjcXR0bfB8=,tag:IXYkUPJS160R1wsMY8FocQ==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:G577+kQShbXQivxKPWJTC4UJruIYDqCmXbpgkD6q,iv:yzH0cnoX1Afhobg4BWpQi3P1zha2s6jzyVkrUsHYQ/A=,tag:CbL4YtXUkAKMo7xFwdBIMg==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ2hmSGM5QkhtZ3k2d21n
            UDJtamZGelhxcE9zTFM5ZlUraGUrSkZGM1NZCm9FMjBnbGY1L1JlV1g2Zi84Yk9G
            bWdVaVV6NXM2ZENsVVN6clNweVNhcHcKLS0tIERCVytBc1cvM3ZqelA2cmQ1MGYy
            YUJhK0NkZytPVStmc2FKaEJ3Q04yZWsKHsQcuFiB86edC9IKNWd7HMWfonnDMZn6
            Tz5xvAXN1JU0IgR6x1LqHxhok7DKPEyHY5LEOnh21jvCyppAQnkJRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T11:22:30Z"
    mac: ENC[AES256_GCM,data:wDrXgPPjxMrlPh61FnBWghVgbIC+W3F5OwYAbwNwMle/495eOIWffTL8+S1HsCbalm074Kk9gzUxYNdgGGDlEE/AKq2Fawrxj83Bg49XSjX/Hz1sQoCBsdo9Q+9Kj39AgSyzmxWXdANmJ0UvF+zLGAnfMfcwfePO8RrljxEOkpI=,iv:zKtMSEJ6ykw2+ctD/b9RaQCxHAsUBCaDEjQEWR3TpKQ=,tag:UvUv4LrGOY14XqBW4ggukA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
