apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:RjUJZ2NbFq2A1HTOaS3heXezRynNX/E6TLUpnq8X/CCTfRZ/kDiOt6Dn1hZGf4tEU7Amgameysa0x8j1foj7DMu54nQU4VDOanIlGpNSBAzeEfxqpibGKIp+3oIW,iv:HQpGvMTeRp9YljvACAiocr1UGKGS0eo/u0O0w1H478E=,tag:CzpAuFaSSOaFg+HEWpDuLA==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ2hmSGM5QkhtZ3k2d21n
            UDJtamZGelhxcE9zTFM5ZlUraGUrSkZGM1NZCm9FMjBnbGY1L1JlV1g2Zi84Yk9G
            bWdVaVV6NXM2ZENsVVN6clNweVNhcHcKLS0tIERCVytBc1cvM3ZqelA2cmQ1MGYy
            YUJhK0NkZytPVStmc2FKaEJ3Q04yZWsKHsQcuFiB86edC9IKNWd7HMWfonnDMZn6
            Tz5xvAXN1JU0IgR6x1LqHxhok7DKPEyHY5LEOnh21jvCyppAQnkJRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T10:51:37Z"
    mac: ENC[AES256_GCM,data:Anq82dH77HOiWLNMHAz6suDYJBLMRakO2dgTOWVtnYMXFgqVmDGaawMp7wxXyBwmqFT5hlPzJJ3zLdqC9MP3ci1Ad9KyHkb9UkVHod6GHGBvzgqgaUVbITEWRkjmwFftbt1ULZ1WQrylN9gM3BIFRkftFoXFT5nFA4Iqxdebmv8=,iv:/F3CxHN6S3AdYTjxDUxDfa4u15hqp1F/X93qNEmgpmU=,tag:Kx6+8iws6rhH7h5CEcS9MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
