---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: renovate-cache
  namespace: renovate
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/renovate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  namespace: renovate
spec:
  volumeName: renovate-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: ""
