---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgresql-cluster
  namespace: cnpg-system
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: local-path
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cn-barman-cloud-cloudflare-object-store
  managed:
    roles:
      - name: app
        createdb: true
        login: true
      - name: miniflux
        createdb: true
        login: true
        superuser: true
        passwordSecret:
          name: miniflux-db-auth
      - name: paperlessngx
        createdb: true
        login: true
        superuser: true
        passwordSecret:
          name: paperless-ngx-db-auth
