---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cn-barman-cloud-cloudflare-object-store
  namespace: default
spec:
  configuration:
    destinationPath: s3://homelab-backups-pg
    endpointURL:
      name: cloudflare-r2-credentials
      key: endpoint-url
    s3Credentials:
      accessKeyId:
        name: cloudflare-r2-credentials
        key: access-key-id
      secretAccessKey:
        name: cloudflare-r2-credentials
        key: access-secret-key
    wal:
      compression: gzip
