---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cn-barman-cloud-cloudflare-object-store
  namespace: cnpg-system
spec:
  retentionPolicy: 14d
  configuration:
    destinationPath: s3://homelab-backups-pg
    endpointURL: https://1fe252835bc6ed045f2ddfbea2933b67.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cloudflare-r2-credentials
        key: access-key-id
      secretAccessKey:
        name: cloudflare-r2-credentials
        key: access-secret-key
    data:
      compression: gzip
      encryption: AES256
    wal:
      compression: gzip
      encryption: AES256
