---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-podcasts
  namespace: audiobookshelf
spec:
  capacity:
    storage: 1800G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool0/media/podcasts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: audiobookshelf
  name: audiobookshelf-podcasts
spec:
  volumeName: audiobookshelf-podcasts
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1800G
  storageClassName: ""
