---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  # skip scheduling of a new job when a prior one is still running
  # make sure only one renovate instance is running at a given time (race conditions)
  # avoids race conditions, duplicate PRs, corrupted cache
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:43.104.5@sha256:5e66d075b24fca40e8fb13886744901c1c55089fbaebe8c8ccf6159d82595bae
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "512Mi"
                limits:
                  memory: "1Gi"
              envFrom:
                - configMapRef:
                    name: renovate-config
                - secretRef:
                    name: renovate-secrets
              volumeMounts:
                - name: renovate-tmp
                  mountPath: /tmp/renovate
                - name: renovate-cache
                  mountPath: /tmp/renovate/cache
          volumes:
            - name: renovate-tmp
              emptyDir: {}
            - name: renovate-cache
              persistentVolumeClaim:
                claimName: renovate-cache
