apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgresql-cluster
spec:
  instances: 3
  storage:
    storageClass: nfs-client
    size: 20Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  enableSuperuserAccess: true
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: "" 
