---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: redis
spec:
  type: oci
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: "22.0.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
  timeout: 10m
  values:
    architecture: replication
    auth:
      existingSecret: redis-auth
      existingSecretPasswordKey: redis-password
    replica:
      replicaCount: 3
