apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: cruxify
type: Opaque
stringData:
    CRUXIFY_SECRET_KEY: ENC[AES256_GCM,data:9Ypsp93p99a8xV0L52TtT+JdrwhlAhMpcahhzjKZiiUoYLVUgq1IQNsRcZI=,iv:TpMMlqjW/BJR70hCsxzRk6TBDSf6t9m3jXaLd90ivNQ=,tag:p2CViF+5XZALx/hTzUtGrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3VjeU5BOFZQdG9ma290
            WU5ZK1UrWGplZ1hHVGJ2NldVMFJUOGQ4VFVFCmg2MzhCTjQ1UGZwWTVZUHNSQ1Br
            ZVZuMHJ6aXd5ZE50cTFzSGlZUEVwTTQKLS0tIEFzSXhhU1VMZkhhNE9JTjVvK0hM
            SkY2SWxEMzlFSms0T252K3VwQ3dnck0K7pBImPBi9p4ISaQ+sSMSLFonM3QYYy4a
            9WxX8IptT7LSyvbku/d9wEXUxOerOZpAatu3+gGtxs/9Coi0A8hflg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T20:33:28Z"
    mac: ENC[AES256_GCM,data:arbnhRdyJZzXjy27K/Ihs2LjAIjLN6vcKRz2da6rDjw5mKaOyh04QRHtiIvHGMPWAxvFOv6WN1wz48HQUOqH/PdZgFxPVbDksherdbk0NaRAy2G8/Kcqc9QNAC33q8ZhNj7l9SgwT6yZnshce0tZn87KYJ2cs8P3+SAPCWFMHdQ=,iv:oGbi3km6VkT4CiltDd0oUKORvDLzQSuJhZWleNnWCyk=,tag:ZsEx2jptxdh46vl1tVlVow==,type:str]
    version: 3.13.3
