apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: cruxify
type: Opaque
stringData:
    CRUXIFY_SECRET_KEY: ENC[AES256_GCM,data:9Ypsp93p99a8xV0L52TtT+JdrwhlAhMpcahhzjKZiiUoYLVUgq1IQNsRcZI=,iv:TpMMlqjW/BJR70hCsxzRk6TBDSf6t9m3jXaLd90ivNQ=,tag:p2CViF+5XZALx/hTzUtGrA==,type:str]
    CRUXIFY_ADMIN_USERNAMES: ENC[AES256_GCM,data:OSRthXgyh0Jq,iv:UtfKS2xu6/6RUyumKp+b052ggMOT5qSwzQXC5SoxxoY=,tag:eMshLRclU+BCZm1fZTunUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab3VjeU5BOFZQdG9ma290
            WU5ZK1UrWGplZ1hHVGJ2NldVMFJUOGQ4VFVFCmg2MzhCTjQ1UGZwWTVZUHNSQ1Br
            ZVZuMHJ6aXd5ZE50cTFzSGlZUEVwTTQKLS0tIEFzSXhhU1VMZkhhNE9JTjVvK0hM
            SkY2SWxEMzlFSms0T252K3VwQ3dnck0K7pBImPBi9p4ISaQ+sSMSLFonM3QYYy4a
            9WxX8IptT7LSyvbku/d9wEXUxOerOZpAatu3+gGtxs/9Coi0A8hflg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T05:24:14Z"
    mac: ENC[AES256_GCM,data:dz3oCx746kXexguhR8SBzWQErNxMt4luZDskLNSKbs80NomTEpfvyipJOTjvtxYl8ubatgcQyYl7xklJjHXSMgL9oOGMgEvrsF8UW4OLY2YveVDlHYgcQtapI09Sxg5o8iMw9aBmUMYqRQ/PWsyoqQlghaE+Y5ivjDlOzwLtR5M=,iv:SR031Ucmd/UyG5Ujc6RnOF3bzoxlFkYEGlqbNnck6zo=,tag:6Sjb4pHZhF9U+PRZaiE3zQ==,type:str]
    version: 3.13.3
