apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: openclaw-secrets
    namespace: openclaw
    labels:
        app: openclaw
stringData:
    FIREWORKS_API_KEY: ENC[AES256_GCM,data:IpKbPbqFgzl1uZN7voLQAW0LyhS15Z74lQmpGHDNiXBb,iv:dM8ABacIK3cxNJqgSm0VOQ0fmgkA+fG2vtbzkmjVIAk=,tag:h5Z2HUh+fVEdNx6LWsrqQw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:OVY4Ksk4afotMPW0e+s+n7NzaQB7HMwzGGVVMq317lEEHe2n5tQKiIiOdQn8WqoMTXVniXbzysh879t37QlZbA==,iv:QIYPGJXBy4yz5c+4sNnbIoIMi98EmyFw/xc0gLcmoi0=,tag:S7x+yaxLEpxfkoKDddQFLg==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NHA5aTR2a082dUM4YmMv
            YXZ0UG5xUVFEVk1IcTdnQlIrdFVYLy9OWjIwCmRlWUVrZWFyREV3QktHbFNySE1h
            VjhuSjd5azNFOE5zS2E4SGhvYUh0VmMKLS0tIHU1ZDJWUWFhZFE3ZEM4RzhZUEdk
            Yzk0R3JpUmo1bXJ5NFhLUnBuY01zNncKLMaBKoDo0v7veb3x7+TT+9ErDOQ+U62W
            KyOJwxfDWYph8pqvw8Q41zTEgnl/h4TuHZQopkeE/jQHY/PIuew2Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T17:08:02Z"
    mac: ENC[AES256_GCM,data:1zbbZZd4u/HCCtMpNvtmZ2oWxQPzp9tu3x8YJ/TAJlejAop2gureGu37S1IqpzstLc460/1uiHyEyZn6Kp2UdzbUMR051Q4RRlA0z1UWnbWJCGaANNQETBMn/BsyRBuTbuf0UwLvo8su+CQk8jeN6C2JIaIFZib7cftpWDtAz6A=,iv:s80XjYqe1gz7LXDfkJ2LOuHNowOAC68HRRZu4XX4JMw=,tag:PMZqUCC5/nLb1jIpjIyXGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
