apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-db-secrets
    namespace: prowlarr
type: Opaque
stringData:
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:cSuaLU6H6hs4k3D+/tZq5VTR+o1Jk7w0Wux4HQKV9JTefzBpXyISziUtwfFseTiEkC4iO5VC,iv:3DIGt9Txg6VuQNs9NkxDRU/diemGgHrlxugpGlTXG0s=,tag:0wqQD8KZGa1nryy1GHGUFQ==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:/M0zsQ==,iv:k0YbQmnNa2z5p4KOzEDYv/nBklSbLUjzVwfViIYyzdQ=,tag:g+gwdrmBckavxTiOPBjTlQ==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:ctOfVg4qiQM=,iv:tj1oEfBUu053ZifOeiTt5SE5BnaGf0BSWV6fuaBJtf0=,tag:8qdxapaj5xyKqodUjBuKdg==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:uOA7RekXoXPO07jMWOFHt/ubEiI7sxxzOUiYNd7YPpZVrtUP+Z3VdQYiktuiQP+c/xc=,iv:rdXtNUomwG2g17ERgI4FwQvfbVW+XcD89OBvAaXcXW4=,tag:3uwhZw/KDKbIqyZY+xka/w==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:jzd6u5l4M/g=,iv:pIbSZ+pJZkIwDapdZCyyAPx/YwbH9YpZ0cBqP7iwlDk=,tag:3at53nxnzsVBWvJ5XmgZHA==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeDlvUTJmTUNHMUVoa3ll
            QTRkdTErTHNsallQS0kzZ0FTUHBIdGRyelc0Ck9VdDZYcTAyQVR5MVphZWZLVE53
            TVZoemd3alMwdU1SVkFjcUk5WGJYQUUKLS0tIDlpbmUzSXAwclpmWjFCeERtOTBK
            dWZ0VVZpY3M2VWVjL2RVTkRFLy9Vd2cKaWe2mrHazmpee4Rg93IEnqQI514so2j2
            m2Yljh1wRx6HspZWn0G5WBDWOvWTO5bnZ48uBxZBqQ9NUJrgNkiaQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T15:33:24Z"
    mac: ENC[AES256_GCM,data:YvpePH/2jSYX377Wll9StBUL06sDNijOWulKym5UHlbNtW//McOx7UY1zKw6r++bAxGcxkYaSf/WNJ6hI3U4QTbazt1IIYIaFpEzvr29/1lkhCUt8Il/xOMGuaVdrmWYSTaNzMQ9M2tfFExX82X5p3JOUvSxsf+DcNlHk6mGd/U=,iv:qfuaDVm6tW4kX+SYQL+Igebz8gej1ohQPSSjSYY00yE=,tag:lHTlJQuj7xRh/CEWF7qm2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
