---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-ngx
  template:
    metadata:
      labels:
        app: paperless-ngx
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:3.2.0@sha256:22dc423ff48ac1629977dbf0c9625ba9f60d3bd1291a2ff173c65351984a14c2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2048Mi
          envFrom:
            - configMapRef:
                name: paperless-ngx-config
            - secretRef:
                name: paperless-ngx-secrets
          volumeMounts:
            - name: paparless-ngx-documents
              mountPath: /mnt/paperless-documents
      volumes:
        - name: paparless-ngx-documents
          persistentVolumeClaim:
            claimName: paperless-ngx-nfs-pvc
