---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless-ngx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  selector:
    matchLabels:
      app: paperless-ngx
  template:
    metadata:
      labels:
        app: paperless-ngx
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:2.18.4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: paperless-ngx-config
            - secretRef:
                name: paperless-ngx-secrets
          volumeMounts:
            - name: paparless-ngx-documents
              mountPath: /mnt/paperless-documents
      volumes:
        - name: paparless-ngx-documents
          persistentVolumeClaim:
            claimName: paperless-ngx-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  labels:
    app: paperless-ngx
spec:
  type: ClusterIP
  selector:
    app: paperless-ngx
  ports:
    - port: 80
      name: http
