---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 10m
  url: https://portainer.github.io/k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: portainer
      version: ce-latest-ee-2.33.2
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: portainer
  releaseName: portainer
