---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beszel-data
  namespace: beszel
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.30
    path: /mnt/pool1/containers/persistent/beszel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-data
  namespace: beszel
spec:
  volumeName: beszel-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: ""
