---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
spec:
  type: ClusterIP
  selector:
    app: portainer
  ports:
    - port: 80
      targetPort: 80
      name: http
