apiVersion: v1
kind: Secret
metadata:
    name: nebula-sync-secrets
    namespace: pihole-nebula-sync
type: Opaque
stringData:
    PRIMARY: ENC[AES256_GCM,data:9gYTM+YjczTcvsYK85TUMm1jBllLt0rvBsjT/UYOhSpYTwvE9iJHJwp9q5px,iv:4j8GeRsDiSFEJdObnWkB9KBRBY12N4MjYfKTVqzrG54=,tag:ujwPKnP45Quk1JbKd8892A==,type:str]
    REPLICAS: ENC[AES256_GCM,data:XM9pbaHZ1o1GOutGrclk22z52HtHOOy8m4gO3+Mkctx4sOypJ/cmWyVIxbIlW4ZD1cFU1cau8iEA,iv:S7/7s6IMAChrYU7jrk7mY1/pe2wucpkjOGYLmj4w/Ms=,tag:d5i18FPlxHaWDN2yPDf7Tw==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ejdvRE9sTlFKdzlwOHFG
            SXBDR0pLc1dibldVWndIU0gxQSszM09aN3hvCkF0NjNJWlJqNVNSeTVZcUowcDhW
            MnVacm96cWNrbjlrcFc5c1ZGT1pZNjgKLS0tIGE3ZjFEMkFRSG5WYVhJRmpKOXo1
            N25uRi9DdVZEd3ZQNExOOU45RWRYUlEKXKk4jFthn3bOcvr5G7aQ5KDbs2c2HtZp
            8H0d5oFNLeScXrlXR76f/nw1Z7Je+fo+w11Kx2metae8UT0jpIjR2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:06:10Z"
    mac: ENC[AES256_GCM,data:tcaWbGCaukHM+t6hzMrTLSfpD6Ltp9gUdHBVisoEBpFp+YyKIbNHGMV9WpGSbtpNbdVWGHXxVMIO2mj4qnfiv5OPIfamhCcssw5bX0X40gXSvjRRtIKS91ZmCNTN6ARUUjW+hP5rCgXQMdP6FkKbEtpEFjtbl/x155CmFuX/TVw=,iv:htyvblOnOiBL3y5O8HgnIJFFD4Qk+FV/VxZcNGGPUww=,tag:6ZIJMpYs18kn246xQKzAww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
