---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nebula-sync
  namespace: pihole-nebula-sync
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: nebula-sync
              image: ghcr.io/lovelaze/nebula-sync:v0.11.1@sha256:e6bb9ac7dbf4471b066cb5db74929c6fa7cfa2251a0682fa85f6da8f687ba4bf
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 50m
                  memory: 32Mi
                limits:
                  memory: 128Mi
              envFrom:
                - configMapRef:
                    name: nebula-sync-config
                - secretRef:
                    name: nebula-sync-secrets
